services:
  api:
    build: .
    container_name: task_tracker_api

    ports:
      - "5000:5000"

    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env

    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: task_tracker_mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: task_tracker_redis

    ports:
      - "6379:6379"

volumes:
  mongo_data: